// Load all the cards to the record page
document.addEventListener('DOMContentLoaded', function () {
    const records = JSON.parse(localStorage.getItem('financeRecords')) || {};
    const calendarContainer = document.querySelector('.calendar-records');
    const monthTitle = document.getElementById('month-title');
    const prevMonthBtn = document.getElementById('prev-month');
    const nextMonthBtn = document.getElementById('next-month');

    // Set initial display month to the current month
    let currentDate = new Date();

    // Format month name and year (e.g., "January 2024")
    // this code generated by ChatGPT
    function formatMonthYear(date) {
        return date.toLocaleString('en-US', { month: 'long', year: 'numeric' });
    }

    // Display records for the selected month
    // this code generated by ChatGPT
    function displayRecordsForMonth() {
        calendarContainer.innerHTML = ''; 

        const selectedMonthYear = formatMonthYear(currentDate);
        monthTitle.textContent = selectedMonthYear;

        // Filter records based on selected month and year
        const filteredRecords = Object.entries(records).filter(([date, data]) => {
            const recordDate = new Date(date);
            return (
                recordDate.getFullYear() === currentDate.getFullYear() &&
                recordDate.getMonth() === currentDate.getMonth()
            );
        });



        // Generate cards for each filtered record
        filteredRecords.forEach(([date, data]) => {
            const { spending, saving } = data;
            const netWorth = saving - spending;

            const card = document.createElement('div');
            card.classList.add('record-entry');

            let netWorthColor = '#141414';

            if (netWorth > 0) {
                card.classList.add('green-border');
                netWorthColor = '#328A35';
            } else if (netWorth < 0) {
                card.classList.add('red-border');
                netWorthColor = '#e74c3c';
            } else {
                card.classList.add('gray-border');
            }

            card.innerHTML = `
                <p class="date">${new Date(date).toDateString()}</p>
                <p class="expense">-$${spending.toFixed(2)}</p>
                <p class="income">+$${saving.toFixed(2)}</p>
                <p class="net-change" style="color: ${netWorthColor};">Net change: $${netWorth.toFixed(2)}</p>
            `;

            calendarContainer.appendChild(card);
        });

        // Display a message if there are no records for the selected month
        if (filteredRecords.length === 0) {
            const message = document.createElement('p');
            message.textContent = "No records found for this month.";
            message.style.color = '#888';
            calendarContainer.appendChild(message);
        }
    }

    function goToPreviousMonth() {
        currentDate.setMonth(currentDate.getMonth() - 1);
        displayRecordsForMonth();
    }

    function goToNextMonth() {
        currentDate.setMonth(currentDate.getMonth() + 1);
        displayRecordsForMonth();
    }

    // Add event listeners for month navigation
    prevMonthBtn.addEventListener('click', goToPreviousMonth);
    nextMonthBtn.addEventListener('click', goToNextMonth);

    // Initial display of records for the current month
    displayRecordsForMonth();
});
